### PR TITLE
Add coverage measurement to Jenkins builds

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
I need to add `curl` to the base image.

**Comment by Rombur** [comment]
@dalg24 if you need to add sth to the base image. Can you wait a little bit, I'll create a PR with things that need to be added to the container.

**Comment by Rombur** [comment]
See #168

**Comment by dalg24** [comment]
@Rombur wrote:
> @dalg24 if you need to add sth to the base image. Can you wait a little bit, I'll create a PR with things that need to be added to the container.

Go ahead and add whatever you like to #170.

**Comment by dalg24** [comment]
In [Jenkins#240](https://jupyterdocker.ornl.gov:8080/job/DataTransferKit-experimental/240/console):
```
./codecov_bash_uploader: line 161: curl: command not found
```
So not going to be able to merge before we add it to the Docker image.

**Comment by dalg24** [comment]
The build shows as passing but the upload to codecov.io clearly failed to upload the coverage report.  This is ridiculous.

**Comment by dalg24** [comment]
Ready for review.

**Pull request merged**
