### PR TITLE
Add CUDA 9.1 pkg version to setup script for nvidia-docker

### PR DESCRIPTION
**Pull request by dalg24**
@sslattery please see if this works on your system

### CODE REVIEW

**Comment by Rombur** [comment]
Don't forget that you won't be able to compile Trilinos with CUDA 9.1. You need the development version of Kokkos to be able to compile Intrepid2 (and the latest version of develop broke something in Trilinos so you need to wait for the fix to be merged in Trilinos).

**Comment by dalg24** [comment]
@Rombur It has nothing to do with the CUDA version you use when you configure DTK/Trilinos.  This has only to do with making development/testing containers CUDA-aware.

**Comment by Rombur** [comment]
I know

**Comment by sslattery** [comment]
Tested and confirmed I was able to extend and build the image with the 9.1 drivers on my system. Explicitly setting `CUDA_VERSION=8.0` also gave a successful build.

**Pull request merged**
