### PR TITLE
Move README from reStructuredTex to Markdown

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
Do you guys want the badges?

**Comment by Rombur** [comment]
Personally I don't care.

**Comment by aprokop** [comment]
What are badges?

**Comment by Rombur** [comment]
Look here https://github.com/ORNL-CEES/Cap all the colorful boxes in the readme

**Comment by aprokop** [comment]
I would add those, then. It's nice to show that everything passes tests, and that there *are* tests.

**Comment by sslattery** [comment]
Is this ready to merge after the badges are added? I do like what you guys have in then CAP readme

**Comment by dalg24** [comment]
Yep ready.  Look [here](https://github.com/dalg24/DataTransferKit/tree/readme) to see what it would look like.  Merge if you like or let me know what you would like to change.

**Comment by sslattery** [comment]
Looks good. Only thing is there is a question mark instead of a badge for the jenkins link in the middle

**Pull request merged**
