### PR TITLE
Fix C API documentation

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by aprokop** [comment]
Is it OK that `DTK_Error` is actually not being used anywhere?

**Comment by dalg24** [comment]
Also I noticed that we only enforce code format on files with extension `.hpp` and `.cpp` so `DTK_C_API.h` is not compliant...

**Comment by sslattery** [comment]
We could have a test that checks the string returned by `DTK_Error`. My tests only check the content of `errno`

**Comment by dalg24** [comment]
```diff
diff --git a/packages/Interface/src/DTK_C_API.h b/packages/Interface/src/DTK_C_API.h
index 397e289..0186189 100644
--- a/packages/Interface/src/DTK_C_API.h
+++ b/packages/Interface/src/DTK_C_API.h
@@ -17,8 +17,8 @@

 #include <DataTransferKit_config.hpp>

-#include <DTK_Types.h>
 #include "DTK_CellTypes.h"
+#include <DTK_Types.h>

 #include <mpi.h>

@@ -33,7 +33,6 @@
 extern "C" {
 #endif

-
 /**
  * \defgroup c_interface_runtime_api C runtime API
  * @{
@@ -111,7 +110,6 @@ extern void DTK_destroyUserApplication( DTK_UserApplicationHandle handle );

 /**@}*/

-
 /**
  * \defgroup c_interface_to_map Interface to maps.
  * @{
@@ -143,8 +141,7 @@ typedef struct _DTK_MapHandle *DTK_MapHandle;
  *
  *  \return DTK_create returns a handle for the map.
  */
-extern DTK_MapHandle DTK_createMap( DTK_ExecutionSpace space,
-                                    MPI_Comm comm,
+extern DTK_MapHandle DTK_createMap( DTK_ExecutionSpace space, MPI_Comm comm,
                                     DTK_UserApplicationHandle source,
                                     DTK_UserApplicationHandle target );

@@ -167,9 +164,8 @@ extern bool DTK_isValidMap( DTK_MapHandle handle );
  *
  *  \param[in] target_field Name of the field in the target application.
  */
-extern void DTK_applyMap( DTK_MapHandle handle,
-                          const char* source_field,
-                          const char* target_field );
+extern void DTK_applyMap( DTK_MapHandle handle, const char *source_field,
+                          const char *target_field );

 /** \brief Destroy a DTK handle to a map.
  *
@@ -179,7 +175,6 @@ extern void DTK_destroyMap( DTK_MapHandle handle );

 /**@}*/

-
 /**
  * \defgroup c_interface_to_dtk_core Initialize/finalize DTK
  * @{
@@ -199,8 +194,8 @@ extern void DTK_initialize();
  *
  *  This version of initialize() effectively calls <code>Kokkos::initialize(
  *  *argc, *argv )</code>.  Pointers to \c argc and \c argv arguments are passed
- *  in order to match MPI_Init's interface.  This function name was suffixed with
- *  _cmd because, unlike C++, C does not allow to overload functions.
+ *  in order to match MPI_Init's interface.  This function name was suffixed
+ * with _cmd because, unlike C++, C does not allow to overload functions.
  *
  *  <!--
  * FIXME: provide a version based on full Kokkos::InitArguments
@@ -252,7 +247,8 @@ extern const char *DTK_error( int err );
 // separate new line.

 /** \brief Passed as the \p type argument to DTK_setUserFunction() in order to
- *  indicate what callback function is being registered with the user application.
+ *  indicate what callback function is being registered with the user
+ * application.
  *
  *  \note Callback functions are passed as pointers to functions that take no
  *  arguments and return nothing (<code>void(*)()</code>) so the value of the
@@ -263,10 +259,20 @@ extern const char *DTK_error( int err );
 typedef enum {
     DTK_NODE_LIST_SIZE_FUNCTION /** See DTK_NodeListSizeFunction() */,
     DTK_NODE_LIST_DATA_FUNCTION /** See DTK_NodeListDataFunction() */,
-    DTK_BOUNDING_VOLUME_LIST_SIZE_FUNCTION /** See DTK_BoundingVolumeListSizeFunction() */,
-    DTK_BOUNDING_VOLUME_LIST_DATA_FUNCTION /** See DTK_BoundingVolumeListDataFunction() */,
-    DTK_POLYHEDRON_LIST_SIZE_FUNCTION /** See DTK_PolyhedronListSizeFunction() */,
-    DTK_POLYHEDRON_LIST_DATA_FUNCTION /** See DTK_PolyhedronListDataFunction() */,
+    DTK_BOUNDING_VOLUME_LIST_SIZE_FUNCTION /** See
+                                              DTK_BoundingVolumeListSizeFunction()
+                                            */
+    ,
+    DTK_BOUNDING_VOLUME_LIST_DATA_FUNCTION /** See
+                                              DTK_BoundingVolumeListDataFunction()
+                                            */
+    ,
+    DTK_POLYHEDRON_LIST_SIZE_FUNCTION /** See DTK_PolyhedronListSizeFunction()
+                                       */
+    ,
+    DTK_POLYHEDRON_LIST_DATA_FUNCTION /** See DTK_PolyhedronListDataFunction()
+                                       */
+    ,
     DTK_CELL_LIST_SIZE_FUNCTION /** See DTK_CellListSizeFunction() */,
     DTK_CELL_LIST_DATA_FUNCTION /** See DTK_CellListDataFunction() */,
     DTK_BOUNDARY_SIZE_FUNCTION /** See DTK_BoundarySizeFunction() */,
@@ -275,8 +281,14 @@ typedef enum {
     DTK_ADJACENCY_LIST_DATA_FUNCTION /** See DTK_AdjacencyListDataFunction() */,
     DTK_DOF_MAP_SIZE_FUNCTION /** See DTK_DOFMapSizeFunction() */,
     DTK_DOF_MAP_DATA_FUNCTION /** See DTK_DOFMapDataFunction() */,
-    DTK_MIXED_TOPOLOGY_DOF_MAP_SIZE_FUNCTION /** See DTK_MixedTopologyDofMapSizeFunction() */,
-    DTK_MIXED_TOPOLOGY_DOF_MAP_DATA_FUNCTION /** See DTK_MixedTopologyDofMapDataFunction() */,
+    DTK_MIXED_TOPOLOGY_DOF_MAP_SIZE_FUNCTION /** See
+                                                DTK_MixedTopologyDofMapSizeFunction()
+                                              */
+    ,
+    DTK_MIXED_TOPOLOGY_DOF_MAP_DATA_FUNCTION /** See
+                                                DTK_MixedTopologyDofMapDataFunction()
+                                              */
+    ,
     DTK_FIELD_SIZE_FUNCTION /** See DTK_FieldSizeFunction() */,
     DTK_PULL_FIELD_DATA_FUNCTION /** See DTK_PullFieldDataFunction() */,
     DTK_PUSH_FIELD_DATA_FUNCTION /** See DTK_PushFieldDataFunction() */,
@@ -341,9 +353,8 @@ typedef void ( *DTK_NodeListDataFunction )( void *user_data,
  *  \param[out] local_num_volumes Number of volumes DTK will allocate memory
  *  for.
  */
-typedef void ( *DTK_BoundingVolumeListSizeFunction )( void *user_data,
-                                                      unsigned *space_dim,
-                                                      size_t *local_num_volumes );
+typedef void ( *DTK_BoundingVolumeListSizeFunction )(
+    void *user_data, unsigned *space_dim, size_t *local_num_volumes );

 /** \brief Prototype function to get the data for a bounding volume list.
  *
@@ -372,8 +383,8 @@ typedef void ( *DTK_BoundingVolumeListDataFunction )(
  */
 typedef void ( *DTK_PolyhedronListSizeFunction )(
     void *user_data, unsigned *space_dim, size_t *local_num_nodes,
-    size_t *local_num_faces, size_t *total_face_nodes,
-    size_t *local_num_cells, size_t *total_cell_faces );
+    size_t *local_num_faces, size_t *total_face_nodes, size_t *local_num_cells,
+    size_t *total_cell_faces );

 /** \brief Prototype function to get the data for a polyhedron list.
  *
@@ -405,9 +416,11 @@ typedef void ( *DTK_PolyhedronListDataFunction )(
  *  \param[out] local_num_cells Number of cells DTK will allocate memory for.
  *  \param[out] total_cell_nodes Total number of nodes for all cells.
  */
-typedef void ( *DTK_CellListSizeFunction )(
-    void *user_data, unsigned *space_dim, size_t *local_num_nodes,
-    size_t *local_num_cells, size_t *total_cell_nodes );
+typedef void ( *DTK_CellListSizeFunction )( void *user_data,
+                                            unsigned *space_dim,
+                                            size_t *local_num_nodes,
+                                            size_t *local_num_cells,
+                                            size_t *total_cell_nodes );

 /** \brief Prototype function to get the data for a mixed topology cell list.
  *
@@ -419,9 +432,10 @@ typedef void ( *DTK_CellListSizeFunction )(
  *  \param[out] cells List of cells.
  *  \param[out] cell_topologies Topologies of the cells.
  */
-typedef void ( *DTK_CellListDataFunction )(
-    void *user_data, Coordinate *coordinates, LocalOrdinal *cells,
-    DTK_CellTopology *cell_topologies );
+typedef void ( *DTK_CellListDataFunction )( void *user_data,
+                                            Coordinate *coordinates,
+                                            LocalOrdinal *cells,
+                                            DTK_CellTopology *cell_topologies );

 /** \brief Prototype function to get the size parameters for a boundary
  *
@@ -457,8 +471,8 @@ typedef void ( *DTK_BoundaryDataFunction )( void *user_data,
  *  \param[in] user_data Pointer to custom user data.
  *  \param[out] total_adjacencies Total number of adjacencies in the list.
  */
-typedef void ( *DTK_AdjacencyListSizeFunction )(
-    void *user_data, size_t *total_adjacencies );
+typedef void ( *DTK_AdjacencyListSizeFunction )( void *user_data,
+                                                 size_t *total_adjacencies );

 /** \brief Prototype function to get the data for an adjacency list.
  *
@@ -474,9 +488,8 @@ typedef void ( *DTK_AdjacencyListSizeFunction )(
  *  has. These serve as offsets into the adjacent_global_cell_ids array.
  */
 typedef void ( *DTK_AdjacencyListDataFunction )(
-    void *user_data, GlobalOrdinal* global_cell_ids,
-    GlobalOrdinal* adjacent_global_cell_ids,
-    unsigned* adjacencies_per_cell );
+    void *user_data, GlobalOrdinal *global_cell_ids,
+    GlobalOrdinal *adjacent_global_cell_ids, unsigned *adjacencies_per_cell );

 /** \brief Prototype function to get the size parameters for a
  *  degree-of-freedom id map with a single number of dofs per object.
```

**Comment by dalg24** [comment]
Merging.  @aprokop and @aprokop please open separate issue as necessary to track your discussion on `DTK_Error` elsewhere.

**Pull request merged**
