### PR TITLE
Wrap radial basis functions (normalize radius)

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
@aprokop C assert I guess then it will execute on CUDA

**Comment by aprokop** [comment]
@dalg24 Have we still not fixed the assert situation? I don't recall.

**Comment by dalg24** [comment]
> fixed the assert situation

Nope

**Comment by Rombur** [comment]
> C assert I guess then it will execute on CUDA

That's not portable: ` It is not supported on MacOS, regardless of the device, and loading a module that references the assert function on Mac OS will fail`

**Comment by dalg24** [comment]
How about a
```C++
// FIXME check precondition radius is greater than zero
```

**Comment by aprokop** [comment]
@dalg24 Sure, this works.

**Comment by dalg24** [comment]
Note that I piggybacked on the PR to remove the Heaviside function that ended up not being used anywhere.  Interestingly this was never reported in the coverage analyses...

**Pull request merged**
