### PR TITLE
Update docker base image

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by aprokop** [comment]
Should have squashed this.

**Comment by dalg24** [comment]
Tests were not passing...

**Comment by dalg24** [comment]
You merged before I pushed 78d68785acf0a4ad33280faebffb26ef3f45c471

**Comment by Rombur** [comment]
You should have put [WIP] if you wanted to do more pushes. Also, I don't see what this PR has anything to do with the tests?

**Comment by aprokop** [comment]
@Rombur Updating the image should mean that the current DTK tests pass in it.

**Comment by dalg24** [comment]
> You should have put [WIP] if you wanted to do more pushes.
My bad.  I only realized the tests were not passing a few second before you merged though.  I ran the tests by hand but here the CI configuration dictionary was bad.
> Also, I don't see what this PR has anything to do with the tests?
This PR is swapping the Docker base image.

**Pull request merged**
