### PR TITLE
Set up continuous integration

### PR DESCRIPTION
**Pull request by dalg24**
This is a work in progress. Please DO NOT MERGE YET.

### CODE REVIEW

**Comment by dalg24** [comment]
test

**Comment by dalg24** [comment]
Ready for your review

**Comment by dalg24** [comment]
``DataTransferKitOperators_SplineInterpolation_test_MPI_4`` is failing

**Comment by dalg24** [comment]
I recommend merging this commit and deal with the test failure separately

**Comment by dalg24** [comment]
CDash server is [here](http://jupyterdocker.ornl.gov/CDash/index.php?project=DataTransferKit)

**Comment by sslattery** [comment]
One question here:

How does docker/configure_trilinos.sh get updated if we change which Trilinos packages we are using? Do we have to do this manually? If so do we see this in a pull request I guess and the build will fail if the file hasn't been updated?

**Comment by dalg24** [comment]
this all have to be updated manually
note that it involves updating the docker image dtk-stk which provides the pre-built environment for the regression

**Pull request merged**
