### PR TITLE
Update license in files to point to the root license

### LINKED ISSUE #196: License definition in source and test files
Currently all source and test files have a very large header stating the DTK BSD 3-clause license which is also defined in the top-level directory in `/LICENSE`. It was suggested to remove this and simply point to the file in `/LICENSE` to remove a substantial amount of code. I would advocate doing this to all new code (i.e. everything going in the `/packages/Kokkos` directory. This would also make license changes in the future much easier. I suggest this top of each file:

```
// DataTransferKit has a BSD 3-Clause open-source software license.
// See the LICENSE file in the top-level directory for the license definition.
```

### PR DESCRIPTION
**Pull request by aprokop**
Fix #196.

### CODE REVIEW

**Comment by sslattery** [comment]
Did we check anywhere to see if this was still a valid way to prescribe an open-source license?

**Comment by aprokop** [comment]
No, we did not. And quick googling does not help.

**Comment by dalg24** [comment]
I looked at root from the cern.  Here is an example https://github.com/root-project/root/blob/master/core/rint/src/TRint.cxx

**Comment by sslattery** [comment]
I like the root example posted by @dalg24. Could we do something more like that instead?

**Comment by aprokop** [comment]
So, something like this?
```
/*************************************************************************
 * Copyright (c) 2012, Stuart R. Slattery                                *
 * All rights reserved.                                                  *
 *                                                                       *
 * For the licensing terms see $DTK/LICENSE.                             * 
 *************************************************************************/
```

**Comment by sslattery** [comment]
Yeah I can't say I love having my name on it like that but that is what the license currently says. We can always change it if we update licenses

**Comment by Rombur** [comment]
In deal, we use  `the deal.II authors` https://github.com/dealii/dealii/blob/master/source/dofs/dof_accessor.cc Also the copyright is range of year from creation to the file to when it was last touched (we use a script to do the update).

**Comment by sslattery** [comment]
OK I like the @Rombur suggestion even better

**Comment by aprokop** [comment]
So, 
```
/*************************************************************************
 * Copyright (c) 2012-2017 by the DTK authors                                *
 * All rights reserved.                                                  *
 *                                                                       *
 * For the licensing terms see $DTK/LICENSE.                             * 
 *************************************************************************/
```

**Comment by sslattery** [comment]
@aprokop Looks good to me

**Comment by aprokop** [comment]
Updated the PR.

**Comment by sslattery** [comment]
Slightly tweaked version

```
/*************************************************************************
 * Copyright (c) 2012-2017 by the DataTransferKit authors                            
 * All rights reserved.                                                  
 *  
 * This file is part of the DataTransferKit library. DataTransferKit has a 
 * BSD 3-clause license. For the licensing terms see the LICENSE file in
 * the top-level directory.                              
 *************************************************************************/
```

**Pull request merged**
