### PR TITLE
Free memory allocated for source and target clouds in Fortran API test

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by Rombur** [comment]
`./docker-run.sh: not found`

**Comment by Rombur** [comment]
My bad, it's DTK 2.0 so we cannot run the tests.

**Comment by sslattery** [comment]
thanks @dalg24

**Comment by dalg24** [comment]
@sslattery Want me to add a suppression file to the repo for the other possible leak from Tpetra?

**Pull request merged**
