### PR TITLE
Fix warning

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Comment by dalg24** [comment]
If you fix
```
tstLinearBVH.cpp(305): warning: variable "x" was set but never used
tstLinearBVH.cpp(305): warning: variable "y" was set but never used
tstLinearBVH.cpp(305): warning: variable "z" was set but never used
```
as well, I am buying you a beer.

**Comment by dalg24** [comment]
How about that one
```
tstInterpolation.cpp(235): warning: pointless comparison of unsigned integer with zero
```

**Comment by Rombur** [comment]
I have fixed the warning in `tstInterpolation.cpp`

**Comment by dalg24** [comment]
@Rombur Do you reckon you know how to resolve `tstLinearBVH.cpp` or should I go ahead and merge as is?

**Comment by Rombur** [comment]
Just merge it

**Comment by dalg24** [comment]
Thank you

**Comment by aprokop** [comment]
This works:
```c++
  double x __attribute__( ( unused ) ), y __attribute__( ( unused ) ), z __attribute__( ( unused ) );               
```

**Comment by dalg24** [comment]
Andrey plz submit PR for it.

**Pull request merged**
