### PR TITLE
Add a not regarding "docker pull" to Developer docs

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Comment by dalg24** [comment]
OK that's messed up, I did a PR #142 to propose changes on that PR.
Now I realize that we both somehow created branches on the ORNL-CEES repo instead of our respective forks.

**Comment by Rombur** [comment]
https://git-scm.com/book/en/v2/Getting-Started-Git-Basics :-D

**Comment by dalg24** [comment]
I tried to do everything through GitHub to save time...

**Comment by aprokop** [comment]
same 😄

**Comment by dalg24** [comment]
Anyway, @aprokop look at the changes I suggested and merge into your PR if you are OK with them.

**Comment by dalg24** [comment]
And let's remove these silly branches.

**Comment by aprokop** [comment]
Not merging in favor of #142.

**Pull request closed without merging**
