### PR TITLE
Count leading zero bits

### PR DESCRIPTION
**Pull request by dalg24**
This PR is essentially moving tree construction utility functions out of `DTK_DetailsAlgorithms.hpp` to a more appropriate place.

**-edit-**
Remain to be done:
- [x] ~~Per @aprokop request, template `clz` on DeviceType.~~ using `#ifdef __CUDA_ARCH__` preprocessor directive instead
- [x] Add comments explaining why using unsigned in CUDA's `__clz` is fine (we use 3 shifted 1023 which is just 30 bits, so never overflow) [*add this comments to both clz() function and next to 1023 magic numbers*]

### CODE REVIEW

**Comment by aprokop** [comment]
Looks good so far, except for stupid doxygen.

**Comment by dalg24** [comment]
I fixed Doxygen.
I see another issue though.  The [`__clz()` CUDA intrinsic](http://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__INT.html#group__CUDA__MATH__INTRINSIC__INT_1gd45548f57952ed410fa5d824984f16d0) takes a signed integer as input parameter and we are using `unsigned int` for the Morton codes...

**Comment by aprokop** [comment]
What about a second comment? Right next to 1023?

**Comment by dalg24** [comment]
Here you go @aprokop

**Comment by aprokop** [comment]
As soon as tests pass, I'm merging it.

**Pull request merged**
