### PR TITLE
Fix a bug: replace Quadrilateral<8> by Quadrilateral<9>

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Comment by dalg24** [comment]
@sslattery @aprokop Do we actually want to have Triangle and Quadrilateral here?  We can add later if we actually want to support 2D.

**Comment by aprokop** [comment]
I would be OK with leaving them out for now.

**Comment by Rombur** [comment]
So you want me to remove it? Why? The code works and there is a test for the 2D case.

**Comment by sslattery** [comment]
We need them - remember the plasma guys have quad and tri meshes on those poloidal planes

**Pull request merged**
