### PR TITLE
Fixes for release 3.0

### PR DESCRIPTION
**Pull request by dalg24**
Pushing #456 and #462 into dtk-3.0

### CODE REVIEW

**Comment by dalg24** [comment]
Also cherry-picked 17e27e5 from #459 for rendering Doxygen documentation on ReadTheDocs

**Comment by Rombur** [comment]
Where is the change on the boost requirement?

**Comment by dalg24** [comment]
Jenkins CI failure is due to codecov submission.

**Comment by dalg24** [comment]
Cherry-picked changes from #464

**Comment by Rombur** [comment]
Cherry-picked changes from #472

**Comment by dalg24** [comment]
Cherry-picked changes from #474 and #475

**Pull request merged**
