### PR TITLE
[WIP] Remove syntax introduced in C99 in C API test

### PR DESCRIPTION
**Pull request by dalg24**
This was giving a compile error with intel 18.
An alternative might be to pass the `-std=c99` flag to the compiler.

### CODE REVIEW

**Comment by dalg24** [comment]
Do not merge yet.  We need to ensure it does not issues new warnings.  Also an alternative solution might be on the CMake side.

**Comment by dalg24** [comment]
This made the trick as well.
```diff
diff --git a/packages/Interface/test/CMakeLists.txt b/packages/Interface/test/CMakeLists.txt
index 40ffc00..708c65b 100644
--- a/packages/Interface/test/CMakeLists.txt
+++ b/packages/Interface/test/CMakeLists.txt
@@ -64,7 +64,15 @@ TRIBITS_ADD_EXECUTABLE(
   C_API_test
   SOURCES tstC_API.c tstC_API.cpp
   COMM serial mpi
+  ADDED_EXE_TARGET_NAME_OUT C_API_test_EXE_TARGET_NAME
   )
+IF (C_API_test_EXE_TARGET_NAME)
+  SET_TARGET_PROPERTIES(
+    ${C_API_test_EXE_TARGET_NAME}
+    PROPERTIES C_STANDARD 99
+  )
+ENDIF()
+

 IF (Kokkos_ENABLE_Serial)
   TRIBITS_ADD_TEST(
```

**Comment by dalg24** [comment]
I am still having issues with `packages/Interface/test/tstView.cpp`.  I get the following error:
```
error: parallel loops with collapse must be perfectly nested
```
L112 and L123 but I cannot make sense out of it.  The code looks fine to me...

**Comment by Rombur** [comment]
Can you try to remove the braces. I wonder if that trips the compiler...

**Comment by dalg24** [comment]
@Rombur No it did not help.  This did the trick though
```diff
diff --git a/packages/Interface/test/tstView.cpp b/packages/Interface/test/tstView.cpp
index 7564397..a3463aa 100644
--- a/packages/Interface/test/tstView.cpp
+++ b/packages/Interface/test/tstView.cpp
@@ -108,10 +108,12 @@ class FillView<Scalar, Kokkos::OpenMP>
         }
         else if ( 2 == num_dims )
         {
+            unsigned const imax = dims[0];
+            unsigned const jmax = dims[1];
 #pragma omp parallel for collapse( 2 )
-            for ( unsigned i = 0; i < dims[0]; ++i )
+            for ( unsigned i = 0; i < imax; ++i )
             {
-                for ( unsigned j = 0; j < dims[1]; ++j )
+                for ( unsigned j = 0; j < jmax; ++j )
                 {
                     dtk_view[j * dims[0] + i] = i + j;
                 }
@@ -119,12 +121,15 @@ class FillView<Scalar, Kokkos::OpenMP>
         }
         else if ( 3 == num_dims )
         {
+            unsigned const imax = dims[0];
+            unsigned const jmax = dims[1];
+            unsigned const kmax = dims[2];
 #pragma omp parallel for collapse( 3 )
-            for ( unsigned i = 0; i < dims[0]; ++i )
+            for ( unsigned i = 0; i < imax; ++i )
             {
-                for ( unsigned j = 0; j < dims[1]; ++j )
+                for ( unsigned j = 0; j < jmax; ++j )
                 {
-                    for ( unsigned k = 0; k < dims[2]; ++k )
+                    for ( unsigned k = 0; k < kmax; ++k )
                     {
                         dtk_view[k * dims[0] * dims[1] + j * dims[0] + i] =
                             i + j + k;
```

**Comment by dalg24** [comment]
Closing in favor of #286

**Pull request closed without merging**
