### PR TITLE
Add support for Crusher

### PR DESCRIPTION
**Pull request by Rombur**
With this PR I can pass the test suite on Crusher. The changes made are:
 - `MapFactory` package has been removed
 - `Interface` package has been removed (not sure what it means for our link with ForTrilinos)
 -  Fix all the instances where we assumed that Unified Memory was enable

### CODE REVIEW

**Comment by masterleinad** [comment]
Why did you remove `MapFactory` and `Interface`?

**Comment by Rombur** [comment]
Because there are not used and the tests assume we use CUDA

**Review by dalg24 — APPROVED** [review]

**Comment by aprokop** [comment]
Are we sure that these are not used by any external users (e.g., ExaAM)?

**Comment by Rombur** [comment]
I thought ExaAm stopped using DTK when they stopped using Truchas

**Comment by aprokop** [comment]
> I thought ExaAm stopped using DTK when they stopped using Truchas

Per John Coleman:
```
I have integrated DTK into a branch of ExaCA, but it is not in the standard release yet. We were using it to interpolate thermal data from a finite volume heat transfer model to a cellular-automata grain structure model for solidification in additive manufacturing
```

**Comment by Rombur** [comment]
That's a C++ code using Kokkos. It's probably cleaner if they don't use the C interface.

**Comment by aprokop** [comment]
I'm not sure how it does that, I have not seen the dtk branch.

**Comment by Rombur** [comment]
John is OK with us removing `Interface`

**Comment by aprokop** [comment]
> John is OK with us removing `Interface`

And `MapFactory`?

**Comment by Rombur** [comment]
Yes  `MapFactory` too.

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
