### PR TITLE
Avoid including Kokkos_Core.hpp in Utils and Search packages

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by aprokop** [comment]
Won't `Kokkos_View.hpp` include `Kokkos_Core.hpp`?

**Comment by dalg24** [comment]
> Won't Kokkos_View.hpp include Kokkos_Core.hpp?

No they include `Kokkos_Core_fwd.hpp`

**Comment by sslattery** [comment]
@dalg24 What was the primary reason for this change?

**Comment by dalg24** [comment]
"Include what you use".

**Pull request merged**
