### PR TITLE
Use Travis CI to build doxygen documentation

### PR DESCRIPTION
**Pull request by dalg24**
Finish addressing #193.

This test will ensure that the Doxygen documentation builds without raising any warnings.
The bad news is that we currently have 86 of them that will need to be resolved.

We can either merge early and fix the warnings later OR wait and push fixes to this PR before we merge.  What do you all think?

### CODE REVIEW

**Comment by dalg24** [comment]
The Travis CI build `doxygen_documentation` did run.  As expected, it is failing.

**Comment by dalg24** [comment]
@sslattery I brought the number of warnings from 86 to 7.  Would you please take care of the few remaining ones?

Note that the Docker image is missing LaTeX at the moment.  I will add it once we get rid of all the current warnings.  Do not merge until I say it is ready.

**Comment by dalg24** [comment]
Here is how to use the Docker image used on our Travis CI build to generate the doc and check for warnings.  From the DTK root dir, run:
```bash
[host]$ docker run --rm -v $PWD:/scratch -w /scratch dalg24/clang-format ./docker/travis/check_doxygen_documentation.sh
```
Consider using `<...> | grep warning:`.

**Comment by dalg24** [comment]
I suggest to make this one blocking for #187.  (Which means we need would need to expedite it.)

**Comment by dalg24** [comment]
Ready for review/merge

**Comment by Rombur** [comment]
OK to merge once jenkins is happy

**Pull request merged**
