### PR TITLE
Format .h and .c source files

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by aprokop** [comment]
@dalg24 Is is possible to add machinery to *exclude* certain files from format-checking? Kind of similar to how git ignores `.gitignore`. I'm thinking that if we have automatically generated files for Fortran interface, formatting them seems to be an extra step that is not necessary.

**Comment by dalg24** [comment]
@aprokop `man grep` :/

**Comment by aprokop** [comment]
@dalg24 I'm not asking in terms of technical difficulty, but rather would people oppose having that?

**Comment by dalg24** [comment]
I am not opposed to it.

**Comment by sslattery** [comment]
I think a `format-ignore` file would be nice

**Pull request merged**
