### PR TITLE
DTKData

### PR DESCRIPTION
**Pull request by dalg24**
Good ole symlink technique will still be good but now we have the option to pass `--recursive` to the `git clone` command.

### CODE REVIEW

**Comment by dalg24** [comment]
This is ready for review/merge.

**Comment by Rombur** [comment]
Since only one libmesh test does not pass and it doesn't have anything to do with this PR, I will merge.

**Comment by Rombur** [comment]
@dalg24 When I approve the request, it means that I am fine for you to merge it if the tests pass.

**Comment by dalg24** [comment]
OK

**Pull request merged**
