### PR TITLE
Cherry-pick of Tweak enable/disable of Fortran_API subpackage

### LINKED ISSUE #160: Configure error when Fortran is not enable
Using `-DTrilinos_ENABLE_Fotran=OFF` should disable the fortran api. Right now it produces the following error:
CMake Error: CMake can not determine linker language for target: dtk_fortran_api
CMake Error in DataTransferKit/packages/Adapters/Fortran_API/src/CMakeLists.txt:
  Exporting the target "dtk_fortran_api" is not allowed since its linker
  language cannot be determined

### PR DESCRIPTION
**Pull request by naughtont3**
Cherry-pick b8a8e5e7bb244c585862588247f453b7a7dc39da to dtk-2.0

Tweak enable/disable of Fortran_API subpackage

Fix #160

Author:    Damien L-G <qdi@ornl.gov>

### CODE REVIEW

**Comment by dalg24** [comment]
OK to test

**Comment by dalg24** [comment]
Jenkins CI failure is expected since DTK-2.0 is missing the docker-compose hooks.
Changes look good to me.

**Comment by naughtont3** [comment]
OK, thanks for clarification. Is there another PR I should cherry-pick to bring the docker-compose over to the dtk-2.0 branch?

**Comment by dalg24** [comment]
> Is there another PR I should cherry-pick to bring the docker-compose over to the dtk-2.0 branch?

Do not worry about this.  It is not a trivial change (mainly because it involves choosing a specific Docker base image to build from and we only started tagging these carefully a short while ago).

**Comment by aprokop** [comment]
Can the same be done automatically with the following change:
```diff
- TRIBITS_SUBPACKAGE(Fortran_API)
+ TRIBITS_SUBPACKAGE(Fortran_API Fortran)
```
in `packages/Adapters/Fortran_API/CMakeLists.txt`?

**Comment by dalg24** [comment]
@naughtont3 Look at #192

**Comment by naughtont3** [comment]
My PR is insufficient for disabling Fortran. It looks like there's something else that implicitly enables Fortran.  

```
-- Setting subpackage enable Trilinos_ENABLE_DataTransferKitFortran_API=ON because parent package Trilinos_ENABLE_DataTransferKit=ON
```

This is not a priority, so may be best to just close/retract this PR.

**Comment by naughtont3** [comment]
Just saw your #192 note and will update PR as per our chat.  Thanks!

**Comment by naughtont3** [comment]
Updated branch as per #192. Rebuilding my trilinos with Fortran=OFF to verify this build successfully and will post status when that completes.

**Comment by naughtont3** [comment]
Trilinos/DTK-2.0 build test with Fortran=OFF passed with this changeset

**Comment by dalg24** [comment]
Thank you Thomas!

**Pull request merged**
