### PR TITLE
Remove -Werror flag from docker_cmake in favor of Jenkins's warning post processor

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by sslattery** [comment]
We will rely on the Jenkins warning post processor to track trends in warnings added from commits.

**Comment by aprokop** [comment]
I think that's a wrong approach unless one is able to see warnings on github. Otherwise who would even look at warnings if builds pass?

**Comment by dalg24** [comment]
The 12.10.1 Trilinos source is not patched in the Docker base image, so each time you start a new container you would not be able to compile unless you apply docker/jenkins/trilinos_stk.patch.

**Comment by aprokop** [comment]
So? Youc could simply patch it in container, or run it with docker-compose.How is it different? And is it the only reason?

**Comment by dalg24** [comment]
I do not want `-Werror` to be the default.  I agree we need a way to back communicate that.  So do we with the execution time...

**Comment by aprokop** [comment]
> I do not want -Werror to be the default.

I'd like to understand why not. Not opposing but curious.

**Pull request merged**
