### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by Rombur**
This PR only update the year in the copyright.

### CODE REVIEW

**Comment by aprokop** [comment]
Can we piggy-back to add  SPDX identifier in this PR?

**Comment by sslattery** [comment]
good catch @Rombur

**Comment by dalg24** [comment]
> Can we piggy-back to add SPDX identifier in this PR?

Fine by me.

**Comment by Rombur** [comment]
done

**Comment by dalg24** [comment]
@Rombur Is it not valid markdown any more?

**Comment by Rombur** [comment]
@dalg24 we are missing the file extension for github to recognize that this markdown

**Comment by dalg24** [comment]
Thank you!

**Pull request merged**
