### PR TITLE
Disable C++ code formatting if unable to download diff-clang-format.py

### PR DESCRIPTION
**Pull request by dalg24**
from GitHub

### CODE REVIEW

**Comment by dalg24** [comment]
@aprokop How do you propose we keep Cap and DTK in sync then?

**Comment by aprokop** [comment]
> How do you propose we keep Cap and DTK in sync then?

Manually if necessary. The fact that changing CAP affects the behavior of DTK is weird as CAP changes may not been tested for DTK.

I understand your reluctance to have two copies of the script, but a) they don't change often, and b) we should get rid of inter-repo dependencies.

**Comment by aprokop** [comment]
I would go further and would make sure that one is able to run all the tests without internet. This means also means addressing `docopt`.

**Comment by dalg24** [comment]
`DataTransferKit_ENABLE_ClangFormat` is OFF by default...

**Comment by dalg24** [comment]
So it is not required to run the tests.

**Pull request merged**
